version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock-app-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    networks:
      - stock-app-network

  # Frontend (Vanilla JS) service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock-app-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - stock-app-network

  # Frontend React service
  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: stock-app-frontend-react
    ports:
      - "3002:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - stock-app-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: stock-app-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
      - frontend-react
    restart: unless-stopped
    networks:
      - stock-app-network

networks:
  stock-app-network:
    driver: bridge

volumes:
  stock-app-data: