version: '3.8'

services:
  # Redis cache service
  redis:
    image: redis:7-alpine
    container_name: stock-app-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - stock-app-network
    volumes:
      - redis-data:/data

  # Backend API service
  backend:
    image: vinsim24/stock-app-backend:latest
    container_name: stock-app-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - stock-app-network

  # Frontend (Vanilla JS) service
  frontend:
    image: vinsim24/stock-app-frontend:latest
    container_name: stock-app-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - stock-app-network

  # Frontend React service
  frontend-react:
    image: vinsim24/stock-app-frontend-react:latest
    container_name: stock-app-frontend-react
    ports:
      - "3002:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - stock-app-network

# Nginx reverse proxy (optional)
  nginx:
    image: nginx:1.29-alpine
    container_name: stock-app-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
      - frontend-react
    restart: unless-stopped
    networks:
      - stock-app-network

networks:
  stock-app-network:
    driver: bridge

volumes:
  stock-app-data:
  redis-data: